### ISSUE TITLE
Tracer v.1.7.2  visibility issue

### ISSUE THREAD

**Issue by haddocksoto** [beast-dev/tracer#175] opened 2022-06-16 16:56 UTC
## Issue with Tracer on MacBook Pro (macOS Catalina 10.15.7)

Tracer 1.7.2 is not working properly Mac OS dark theme. It doesn't show the traces on the left nor the analysis on the right unless I 
hover my mouse around it.

<img width="1195" alt="Screen Shot 2022-06-16 at 11 53 24 AM" src="https://user-images.githubusercontent.com/55507927/174124835-284d7d4e-3f68-4cb1-8163-290e76caa55b.png">

**Comment by haddocksoto** [comment] 2022-06-16 19:56
The issue persists even after upgrading to macOS Monterey 12.4

**Comment by duckien242** [comment] 2022-07-08 14:38
. I am also running into the same issue, would appreciate any assistance
<img width="1765" alt="Screen Shot 2022-07-08 at 10 33 50 AM" src="https://user-images.githubusercontent.com/89991650/178014067-ea6635dc-78ec-4de5-86e3-c853f468a913.png">

**Comment by esnielsen** [comment] 2023-01-18 21:27
Hi- I am facing the same issue, did you happen to find a solution? Thanks!

**Comment by haddocksoto** [comment] 2023-01-18 22:06
Hi @esnielsen 

I worked around the issue by using version 1.7.1.

Version 1.7.2 is still giving me the same issues

**Comment by walterxie** [comment] 2023-01-18 22:06
Hi everyone, I cannot replicate this problem. I am suspecting the log file to cause the problem was corrupt, which makes Tracer crash. Can anyone upload an example log file to reproduce this problem?

**Comment by esnielsen** [comment] 2023-01-18 22:11
Thank you!!

**Comment by walterxie** [comment] 2023-01-18 22:13
@esnielsen cannot see any files. I think you have to upload manually through GitHub issue website, not from email, if you had sent me a file.

**Comment by rambaut** [comment] 2023-04-27 11:35
Tested with latest 12.5.1 Monterey on an M1 mac using zulu-17.jdk and does not seem to be an issue. It may be specific to a JVM (which would not have an easy solution - other than to use a different JVM). Closing for now.

**Closed by rambaut** 2023-04-27 11:35 UTC
